[32mINFO    [0m root:test_login.py:29 User is able to login successfully